# JUPYTER NOTE BOOK PRACTCE

#### Youtube course 'DATA ANALYSIS USING PYTHON' by freecodecamp.org 

In [3]:
3+5

8

# NUMPY


In [5]:
import sys
import numpy as np

In [6]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [7]:
a = np.array([1, 2, 3, 4], dtype=np.int8)

In [8]:
b = np.array([0, 0.5, 1, 1.5, 2])

In [9]:
a[0], a[1]

(np.int8(1), np.int8(2))

In [10]:
a[0:]

array([1, 2, 3, 4], dtype=int8)

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [12]:
A = np.array([[1,2,3],[4,5,6]])

In [13]:
A.shape

(2, 3)

In [14]:
A.ndim

2

In [15]:
A.size

6

In [17]:
B = np.array([
    [
        [12,11,10],
        [9,8,7],
    ],
        
        [
            [6,5,4],
         [3,2,1]
         ]
         
])

In [18]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [ ]:
B.shape

(2, 2, 3)

In [21]:
B.ndim


3

In [26]:
B[:][:2][2:]

array([], shape=(0, 2, 3), dtype=int64)

## Numpy Vectors


In [ ]:
B.sum(axis=1)

array([[21, 19, 17],
       [ 9,  7,  5]])

In [37]:
a= np.arange(4)

In [38]:
a

array([0, 1, 2, 3])

In [39]:
a+10

array([10, 11, 12, 13])

In [40]:
a*10

array([ 0, 10, 20, 30])

In [41]:
a

array([0, 1, 2, 3])

In [42]:
a+=10

In [43]:
a

array([10, 11, 12, 13])

In [ ]:
a=np.arange(4)

In [ ]:
b=np.array([10,10,10,10])

In [46]:
b

array([10, 10, 10, 10])

In [47]:
a*b

array([ 0, 10, 20, 30])

In [48]:
a+b

array([10, 11, 12, 13])

## Boolean arrays

In [ ]:
a=np.arange(4)

In [50]:
a[[0,-1]]

array([0, 3])

In [ ]:
a[[True,False,False,True]]

array([0, 3])

In [52]:
a>=2

array([False, False,  True,  True])

In [55]:
a[a>=2]

array([2, 3])

In [56]:
a.mean()

np.float64(1.5)

## Linear Algebra

In [57]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [58]:
B=np.array([[6,5],[4,3],[2,1]])

In [ ]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [60]:
A @ B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [61]:
B.T

array([[6, 4, 2],
       [5, 3, 1]])

## Size of objects in Memory

In [ ]:
sys.getsizeof(1)

28

In [68]:
np.dtype(np.int16).itemsize

2